### ISSUE TITLE
Tuya configuration

### ISSUE THREAD

**Issue by BreizhCat** [papo-o/home-assistant-config#1]
Bonjour 

J'ai également des produits tuya. 2 prises. Mais je n'ai jamais réussi à trouver le bon moyen pour récupérer les identifiants. 
Quelle(s) méthode(s) avez-vous utilisée(s) ? 

Merci.

**Comment by papo-o** [comment]
Bonjour,
j'ai appairé mes 4 prises via l'application smart life dispo sur ios et android.
j'ai paramétré HA comme ceci

tuya:
  username: l'adresse mail utilisé dans l'appli
  password: le mot de passe de l'appli
  country_code: 33
  platform: smart_life
après un redémarrage  les périphériques remontent directement sous forme de sensors

**Comment by BreizhCat** [comment]
Bonjour

Merci pour votre réponse. Je vais regarder cela du coup. 
Car je pensais qu'il fallait faire la même démarche que pour domoticz où je n'ai pas réussi à mettre mes prises.

Il faut que je teste HA du coup plus sérieusement.

**Comment by papo-o** [comment]
la méthode domoticz permet de s'affranchir du cloud  via la création d'un serveur personnel, ce qui n'est pas le cas avec HA

**Comment by BreizhCat** [comment]
Bonjour

Merci pour votre dernier message. Je comprends mieux le problème. 
Bonne journée
