### ISSUE TITLE
Darksky

### ISSUE THREAD

**Issue by yoks33** [papo-o/home-assistant-config#2]
Bonjour Papo,

Auriez vous une idée svp  pour remplacer les prévisions darksky sous domoticz depuis le rachat par Apple ça ne fonctionne plus. j'ai chercher sur le net mais je ne trouve rien.  si vous avez une solution je vous en remercie par avance.

**Comment by papo-o** [comment]
bonjour, 
vous êtes dans la section home assistant de mon github. celui dédié à domoticz est la : https://github.com/papo-o/domoticz_scripts.
darksky fonctionne encore chez moi ( surement plus pour longtemps). je n'ai pas cherché de solution pour domoticz, testant home assistant qui dispose d'une implémentation de l'API https://www.weatherbit.io/
