### ISSUE TITLE
Les infos ne remontent plus

### ISSUE THREAD

**Issue by Nintendax69** [papo-o/home-assistant-config#4]
Bonjour papo-o, merci pour ce scrape d'horoscopes, par contre depuis quelques temps il ne fonctionne plus j'ai cette erreur : 
Logger: homeassistant.components.scrape.sensor
Source: components/scrape/sensor.py:181
Integration: scrape (documentation, issues)
First occurred: 13:19:43 (36 occurrences)
Last logged: 19:19:49

Unable to extract data from HTML for scrape Sagittaire
Unable to extract data from HTML for scrape Capricorne
Unable to extract data from HTML for scrape Verseau
Unable to extract data from HTML for scrape Gemeaux
Unable to extract data from HTML for scrape Lion
sauriez-vous pourquoi ?
Merci pour votre retour

**Comment by papo-o** [comment]
Bonjour
Le site a changé de format
j'ai modifié le script en conséquence

**Comment by Nintendax69** [comment]
Merci beaucoup pap-o, je vais le remettre alors 😁

⁣Télécharger BlueMail pour Android ​

Le 13 nov. 2021 à 00:47, à 00:47, papo-o ***@***.***> a écrit:
